"""Timeanchored Alignment 服务入口。"""

from app.services.timeanchored_alignment.contracts import (
    CONTRACT_VERSION,
    ALLOWED_ALIGNMENT_ROUTES,
    ALLOWED_ALIGNMENT_STATUS,
    AcousticCandidate,
    AlignmentItem,
    AlignmentMetrics,
    FinalAlignmentResult,
    LayerReport,
    PhoneticPackage,
    PhoneticUnit,
    PipelineReport,
    ProtectedSpan,
    SlowInferenceWindow,
    SlowInferenceWindowEnvelope,
    TextTruthPackage,
    TextTruthQuality,
    TextTruthUnit,
    TimeBasePackage,
    TimeBaseQuality,
    TimeBaseUnit,
)
from app.services.timeanchored_alignment.time_base_builder import TimeBaseBuilder

__all__ = [
    "CONTRACT_VERSION",
    "ALLOWED_ALIGNMENT_ROUTES",
    "ALLOWED_ALIGNMENT_STATUS",
    "AcousticCandidate",
    "AlignmentItem",
    "AlignmentMetrics",
    "FinalAlignmentResult",
    "LayerReport",
    "PhoneticPackage",
    "PhoneticUnit",
    "PipelineReport",
    "ProtectedSpan",
    "SlowInferenceWindow",
    "SlowInferenceWindowEnvelope",
    "TextTruthPackage",
    "TextTruthQuality",
    "TextTruthUnit",
    "TimeBaseBuilder",
    "TimeBasePackage",
    "TimeBaseQuality",
    "TimeBaseUnit",
]
