"""Timeanchored Alignment 服务入口。"""

from app.services.timeanchored_alignment.contracts import (
    CONTRACT_VERSION,
    ALLOWED_ALIGNMENT_ROUTES,
    ALLOWED_ALIGNMENT_STATUS,
    AcousticCandidate,
    AlignmentItem,
    AlignmentMetrics,
    FinalAlignmentResult,
    LanguageRun,
    LanguageRunPackage,
    LayerReport,
    PhoneUnit,
    PronunciationPackage,
    TokenToPhoneSpan,
    TokenUnit,
    PhoneticPackage,
    PhoneticUnit,
    PipelineReport,
    ProtectedSpan,
    SlowInferenceWindow,
    SlowInferenceWindowEnvelope,
    TextTruthPackage,
    TextTruthQuality,
    TextTruthUnit,
    TimeBasePackage,
    TimeBaseQuality,
    TimeBaseUnit,
)
from app.services.timeanchored_alignment.hint_builder import HintBuilder
from app.services.timeanchored_alignment.language_run_frontend import LanguageRunFrontend
from app.services.timeanchored_alignment.pronunciation_frontend import PronunciationFrontend
from app.services.timeanchored_alignment.slow_window_assembler import (
    SlowWindowAssembler,
    SlowWindowAssemblerConfig,
)
from app.services.timeanchored_alignment.time_base_builder import TimeBaseBuilder
from app.services.timeanchored_alignment.turn_group_adapter import TurnGroupAdapter
from app.services.timeanchored_alignment.window_language_classifier import (
    MAIN_CHAIN_DECISION_DOMAINS,
    MIXED_DECISION_DOMAINS,
    WindowLanguageClassifier,
    WindowLanguageDecision,
)

__all__ = [
    "CONTRACT_VERSION",
    "ALLOWED_ALIGNMENT_ROUTES",
    "ALLOWED_ALIGNMENT_STATUS",
    "AcousticCandidate",
    "AlignmentItem",
    "AlignmentMetrics",
    "FinalAlignmentResult",
    "LanguageRun",
    "LanguageRunPackage",
    "LayerReport",
    "PhoneUnit",
    "PronunciationPackage",
    "TokenToPhoneSpan",
    "TokenUnit",
    "PhoneticPackage",
    "PhoneticUnit",
    "PipelineReport",
    "ProtectedSpan",
    "HintBuilder",
    "LanguageRunFrontend",
    "PronunciationFrontend",
    "SlowWindowAssembler",
    "SlowWindowAssemblerConfig",
    "SlowInferenceWindow",
    "SlowInferenceWindowEnvelope",
    "TextTruthPackage",
    "TextTruthQuality",
    "TextTruthUnit",
    "TimeBaseBuilder",
    "TurnGroupAdapter",
    "TimeBasePackage",
    "TimeBaseQuality",
    "TimeBaseUnit",
    "WindowLanguageClassifier",
    "WindowLanguageDecision",
    "MIXED_DECISION_DOMAINS",
    "MAIN_CHAIN_DECISION_DOMAINS",
]
