"""Timeanchored Alignment 服务入口。"""

from app.services.timeanchored_alignment.contracts import (
    CONTRACT_VERSION,
    ALLOWED_ALIGNMENT_ROUTES,
    ALLOWED_ALIGNMENT_STATUS,
    AcousticCandidate,
    AlignmentItem,
    BoundaryEvidence,
    AlignmentMetrics,
    FinalAlignmentResult,
    LanguageRun,
    LanguageRunPackage,
    LayerReport,
    PhoneUnit,
    PronunciationPackage,
    TokenToPhoneSpan,
    TokenUnit,
    PhoneticPackage,
    PhoneticUnit,
    PipelineReport,
    ProtectedSpan,
    SlowInferenceWindow,
    SlowInferenceWindowEnvelope,
    TextTruthPackage,
    TextTruthQuality,
    TextTruthUnit,
    TimeBasePackage,
    TimeBaseQuality,
    TimeBaseUnit,
)
from app.services.timeanchored_alignment.hint_builder import HintBuilder
from app.services.timeanchored_alignment.language_run_frontend import LanguageRunFrontend
from app.services.timeanchored_alignment.pronunciation_frontend import PronunciationFrontend
from app.services.timeanchored_alignment.phonetic_aligner import (
    PhoneticAligner,
    PhoneticAlignerConfig,
    PhoneticRescueResult,
    PhoneticRescueTrace,
)
from app.services.timeanchored_alignment.phonetic_matchers import (
    PhoneticAlignmentPair,
    align_monotonic_sequences,
    project_token_phone_keys,
)
from app.services.timeanchored_alignment.slow_window import (
    DialogueShapeSnapshot,
    PromptSeed,
    ReadySlowWindow,
    SlowWindowBuilder,
    SlowWindowBuilderConfig,
    SlowWindowIngressAdapter,
    SlowWindowIngressUnit,
    WindowBatchHint,
    WindowChunkBinding,
    WindowCoverage,
    WindowLanguageProfile,
    WindowSourceUnit,
)
from app.services.timeanchored_alignment.chunk_projector import (
    ChunkWindow,
)
from app.services.timeanchored_alignment.preparation import (
    AlignmentPreparationAssembler,
    AlignmentPreparationCompat,
    AlignmentPreparationPackage,
    FastHook,
    PreparedSlowText,
    PronunciationHint,
    ProtectedUnit,
    PunctuationEvidence,
    SlowSlot,
    SlowWindowTextPackage,
)
from app.services.timeanchored_alignment.text_alignment_scoring import (
    TextAlignmentScoreBreakdown,
    TextAlignmentScoreConfig,
    TextAlignmentScorer,
)
from app.services.timeanchored_alignment.hallucination_gate import (
    BOTH_SIDES_UNAVAILABLE_ERROR,
    GateDecision,
    GateEvaluation,
    HallucinationGate,
    HallucinationGateConfig,
)
from app.services.timeanchored_alignment.time_base_builder import TimeBaseBuilder
from app.services.timeanchored_alignment.window_time_base_assembler import (
    WindowTimeBaseAssembler,
    WindowTimeBasePackage,
)
from app.services.timeanchored_alignment.window_language_classifier import (
    MAIN_CHAIN_DECISION_DOMAINS,
    MIXED_DECISION_DOMAINS,
    WindowLanguageClassifier,
    WindowLanguageDecision,
)

__all__ = [
    "CONTRACT_VERSION",
    "ALLOWED_ALIGNMENT_ROUTES",
    "ALLOWED_ALIGNMENT_STATUS",
    "AcousticCandidate",
    "AlignmentItem",
    "BoundaryEvidence",
    "AlignmentMetrics",
    "FinalAlignmentResult",
    "LanguageRun",
    "LanguageRunPackage",
    "LayerReport",
    "PhoneUnit",
    "PronunciationPackage",
    "TokenToPhoneSpan",
    "TokenUnit",
    "PhoneticPackage",
    "PhoneticUnit",
    "PipelineReport",
    "ProtectedSpan",
    "HintBuilder",
    "LanguageRunFrontend",
    "PronunciationFrontend",
    "PhoneticAligner",
    "PhoneticAlignerConfig",
    "PhoneticRescueResult",
    "PhoneticRescueTrace",
    "PhoneticAlignmentPair",
    "align_monotonic_sequences",
    "project_token_phone_keys",
    "BOTH_SIDES_UNAVAILABLE_ERROR",
    "GateDecision",
    "GateEvaluation",
    "HallucinationGate",
    "HallucinationGateConfig",
    "TextAlignmentScorer",
    "TextAlignmentScoreConfig",
    "TextAlignmentScoreBreakdown",
    "DialogueShapeSnapshot",
    "PromptSeed",
    "ReadySlowWindow",
    "SlowWindowBuilder",
    "SlowWindowBuilderConfig",
    "SlowWindowIngressAdapter",
    "SlowWindowIngressUnit",
    "ChunkWindow",
    "AlignmentPreparationAssembler",
    "AlignmentPreparationCompat",
    "AlignmentPreparationPackage",
    "FastHook",
    "PreparedSlowText",
    "PronunciationHint",
    "ProtectedUnit",
    "PunctuationEvidence",
    "SlowSlot",
    "SlowWindowTextPackage",
    "SlowInferenceWindow",
    "SlowInferenceWindowEnvelope",
    "TextTruthPackage",
    "TextTruthQuality",
    "TextTruthUnit",
    "TimeBaseBuilder",
    "TimeBasePackage",
    "TimeBaseQuality",
    "TimeBaseUnit",
    "WindowBatchHint",
    "WindowChunkBinding",
    "WindowCoverage",
    "WindowLanguageClassifier",
    "WindowLanguageDecision",
    "WindowLanguageProfile",
    "WindowSourceUnit",
    "WindowTimeBaseAssembler",
    "WindowTimeBasePackage",
    "MIXED_DECISION_DOMAINS",
    "MAIN_CHAIN_DECISION_DOMAINS",
]
